<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>S1135</WarningsNotAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\..\..\..\Users\kvvin\.nuget\packages\pds.core.codeanalysis.stylecop\1.0.0\stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestEmbeddedResources\TestJavaScriptWithVar.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="TestEmbeddedResources\TestJavaScriptWithFunction.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="TestEmbeddedResources\TextResourceFile2.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="TestEmbeddedResources\TextResourceFile1.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="FluentAssertions" Version="7.2.0" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
	<PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
	<PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
	<PackageReference Include="coverlet.collector" Version="6.0.4">
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		<PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Pds.Core.CodeAnalysis.StyleCop" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pds.DocumentExchange.Data.Repository\Pds.DocumentExchange.Data.Repository.csproj" />
  </ItemGroup>

</Project>
