<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904;S1135</WarningsNotAsErrors>
	<LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Example.docx" />
    <None Remove="Assets\Example_100KB.docx" />
    <None Remove="Assets\Example_120KB.docx" />
    <None Remove="Assets\Example_1240KB.docx" />
    <None Remove="Assets\Example_150KB.docx" />
    <None Remove="Assets\Example_200KB.docx" />
    <None Remove="Assets\Example_400KB.docx" />
    <None Remove="Assets\Example_450KB.docx" />
    <None Remove="Assets\Example_50KB.docx" />
    <None Remove="Assets\Example_600KB.docx" />
    <None Remove="Assets\Example_700KB.docx" />
    <None Remove="Assets\Example_800KB.docx" />
    <None Remove="Assets\Example_80KB.docx" />
    <None Remove="Assets\Example_900KB.docx" />
    <None Remove="bulkDelete.js" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Example.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_100KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_120KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_1240KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_150KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_200KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_400KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_450KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_50KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_600KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_700KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_800KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_80KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Example_900KB.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="bulkDelete.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.22.0" />
    <PackageReference Include="CsvHelper" Version="32.0.3" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.52.1" />
    <PackageReference Include="Pds.Core.ApiAuthentication" Version="2.0.2" />
    <PackageReference Include="Pds.Core.BulkJobs.Redis" Version="2.0.0" />
    <PackageReference Include="Pds.Core.CodeAnalysis.StyleCop" Version="2.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pds.DocumentExchange.Data.Services\Pds.DocumentExchange.Data.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
